
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 3
      minIdle: 5
      maxActive: 20

      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000

      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties.druid.stat.mergeSql.true;druid.stat.slowSqlMillis: 10000

#    mvc:
#       view:
#          prefix: /
#          suffix: .jsp
#       static-path-pattern: /resources/**
#       这个配置会影响默认的/，例如修改为/static/后，只能映射如/static/js/sample.js这样的请求（修改前是/js/sample.js）。这个配置只能写一个值，不像大多数可以配置多个用逗号隔开的。


    redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
    thymeleaf:
      prefix: classpath:/static/
      suffix: .html
      servlet:
        content-type: text/html
      cache: false
    #     spring.thymeleaf.prefix=classpath:/templates/
    #     spring.thymeleaf.suffix=.html
    #     spring.thymeleaf.mode=LEGACYHTML5
    #     spring.thymeleaf.encoding=UTF-8
    #     spring.thymeleaf.content-type=text/html
    #     spring.thymeleaf.cache=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.toommi.demo.domain
server:
  port: 80