
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: jiaorpeng

# 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


#    mvc:
#       view:
#          prefix: /
#          suffix: .jsp
#       static-path-pattern: /resources/**
#       这个配置会影响默认的/，例如修改为/static/后，只能映射如/static/js/sample.js这样的请求（修改前是/js/sample.js）。这个配置只能写一个值，不像大多数可以配置多个用逗号隔开的。


    redis:
        host: localhost
        port: 6379
        jedis:
          pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.toommi.demo.domain
server:
  port: 8080